version: '3.8'
services:
  db:
    image: mysql:9.2
    container_name: calendar_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: calendar
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
